package view.viewTest;

import javax.swing.*;
import java.awt.*;

public class VFrame extends JFrame
{
    private JPanel menuPanel;
    private JButton button1;
    private JButton button2;
    private JPanel showPanel;
    private JLabel label1;

    public VFrame()
    {
        add(menuPanel);

        setTitle("Hello");
        setSize(500,500);
    }

    public JPanel getMenuPanel()
    {
        return menuPanel;
    }

    public void setMenuPanel(JPanel menuPanel)
    {
        this.menuPanel = menuPanel;
    }

    public JButton getButton1()
    {
        return button1;
    }

    public void setButton1(JButton button1)
    {
        this.button1 = button1;
    }

    public JButton getButton2()
    {
        return button2;
    }

    public void setButton2(JButton button2)
    {
        this.button2 = button2;
    }

    public JPanel getShowPanel()
    {
        return showPanel;
    }

    public void setShowPanel(JPanel showPanel)
    {
        this.showPanel = showPanel;
    }

    public JLabel getLabel1()
    {
        return label1;
    }

    public void setLabel1(JLabel label1)
    {
        this.label1 = label1;
    }

    /**
     {
     // GUI initializer generated by IntelliJ IDEA GUI Designer
     // >>> IMPORTANT!! <<<
     // DO NOT EDIT OR ADD ANY CODE HERE!
     $$$setupUI$$$();
     }


     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
   /* private void $$$setupUI$$$()
    {
        menuPanel = new JPanel();
        menuPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        menuPanel.setPreferredSize(new Dimension(300, 300));
        button1 = new JButton();
        button1.setText("Button");
        menuPanel.add(button1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button2 = new JButton();
        button2.setText("Button");
        menuPanel.add(button2, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        showPanel = new JPanel();
        showPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        menuPanel.add(showPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    *//**
 * @noinspection ALL
 *//*
    public JComponent $$$getRootComponent$$$() { return menuPanel; }*/
}

